# Generated by Django 3.2.12 on 2022-03-18 09:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Значение')),
                ('currency', models.CharField(choices=[('USD', 'United States Dollar')], max_length=3, verbose_name='Валюта')),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='Идентификатор транзакции')),
                ('state', models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('canceled', 'canceled')], max_length=30, verbose_name='Состояние транзакции')),
                ('cancelation_reason', models.TextField(blank=True, null=True, verbose_name='Причина отмены')),
                ('payment_system_id', models.CharField(max_length=100, verbose_name='Идентификатор платежной системы')),
                ('payment_system_transaction_id', models.CharField(max_length=100, verbose_name='Идентификатор транзакции в платежной системе')),
                ('confirmation_url', models.URLField(verbose_name='Ссылка для подтверждения')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='wallets.wallet', verbose_name='Кошелек')),
            ],
        ),
    ]
