# Generated by Django 3.2.12 on 2022-03-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deposits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="confirmation_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка для подтверждения"
            ),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("pending", "pending"),
                    ("succeeded", "succeeded"),
                    ("canceled", "canceled"),
                ],
                max_length=30,
                verbose_name="Состояние транзакции",
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="state",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("pending", "pending"),
                    ("succeeded", "succeeded"),
                    ("canceled", "canceled"),
                ],
                max_length=30,
                verbose_name="Состояние транзакции",
            ),
        ),
    ]
