# Generated by Django 3.2.12 on 2022-03-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        decimal_places=4, max_digits=19, verbose_name="Депозит"
                    ),
                ),
                (
                    "hold",
                    models.DecimalField(
                        decimal_places=4, max_digits=19, verbose_name="Холд"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "United States Dollar")],
                        max_length=3,
                        verbose_name="Валюта",
                    ),
                ),
            ],
        ),
    ]
