# Generated by Django 3.2.12 on 2022-03-20 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_system_id",
                    models.CharField(max_length=100, verbose_name="Payment system ID"),
                ),
                (
                    "payment_system_account_number",
                    models.CharField(
                        max_length=100, verbose_name="Payment system account number"
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        decimal_places=4, max_digits=19, verbose_name="Deposit"
                    ),
                ),
                (
                    "hold",
                    models.DecimalField(
                        decimal_places=4, max_digits=19, verbose_name="Hold"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "United States Dollar")],
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
            ],
        ),
    ]
