# Generated by Django 3.2.12 on 2022-03-20 04:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wallets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=19, verbose_name="Value"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "United States Dollar")],
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("pending", "pending"),
                            ("succeeded", "succeeded"),
                            ("canceled", "canceled"),
                        ],
                        max_length=30,
                        verbose_name="Transaction state",
                    ),
                ),
                (
                    "cancelation_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Cancelation reason"
                    ),
                ),
                (
                    "payment_system_id",
                    models.CharField(max_length=100, verbose_name="Payment system ID"),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="wallets.wallet",
                        verbose_name="Wallet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=19, verbose_name="Value"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "United States Dollar")],
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "transaction_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "created"),
                            ("pending", "pending"),
                            ("succeeded", "succeeded"),
                            ("canceled", "canceled"),
                        ],
                        max_length=30,
                        verbose_name="Transaction state",
                    ),
                ),
                (
                    "cancelation_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Cancelation reason"
                    ),
                ),
                (
                    "payment_system_id",
                    models.CharField(max_length=100, verbose_name="Payment system ID"),
                ),
                (
                    "confirmation_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Confirmation URL"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deposits",
                        to="wallets.wallet",
                        verbose_name="Wallet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
