# Generated by Django 3.2.12 on 2022-03-20 05:02

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="transaction_id",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="Transaction ID"
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="transaction_id",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="Transaction ID"
            ),
        ),
    ]
